/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 23 груд 2011, 12:32:08
 */
package jtvprog;

/**
 *
 * @author Stanislav Nepochatov
 */
public class mainFrame extends javax.swing.JFrame {

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
        this.setVisible(true);
        JTVProg.logPrint("mainFrame", 3, "показ главного окна");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tvchTable = new javax.swing.JTable();
        tvFillBut = new javax.swing.JButton();
        tvProcBut = new javax.swing.JButton();
        tvReleaseBut = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();
        tvBar = new javax.swing.JMenuBar();
        tvSettings = new javax.swing.JMenu();
        tvchSettings = new javax.swing.JMenuItem();
        tvchReleaseOrder = new javax.swing.JMenuItem();
        tvDeleteFiles = new javax.swing.JMenuItem();
        tvOther = new javax.swing.JMenu();
        tvHelp = new javax.swing.JMenuItem();
        tvAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Обработчик телепрограммы");

        tvchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Канал", "Сохранен?", "Обработан?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tvchTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tvchTable);

        tvFillBut.setText("(1) Заполнить");

        tvProcBut.setText("(2) Обработать");
        tvProcBut.setEnabled(false);

        tvReleaseBut.setText("(3) Выпустить");
        tvReleaseBut.setEnabled(false);

        exitBut.setText("Выход");
        exitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButActionPerformed(evt);
            }
        });

        tvSettings.setText("Настройки");

        tvchSettings.setText("Редактировать список настроек");
        tvSettings.add(tvchSettings);

        tvchReleaseOrder.setText("Порядок выпуска");
        tvchReleaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvchReleaseOrderActionPerformed(evt);
            }
        });
        tvSettings.add(tvchReleaseOrder);

        tvDeleteFiles.setText("Удалить файлы");
        tvSettings.add(tvDeleteFiles);

        tvBar.add(tvSettings);

        tvOther.setText("Справка");

        tvHelp.setText("Помощь");
        tvOther.add(tvHelp);

        tvAbout.setText("О программе");
        tvOther.add(tvAbout);

        tvBar.add(tvOther);

        setJMenuBar(tvBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tvFillBut)
                        .addGap(18, 18, 18)
                        .addComponent(tvProcBut)
                        .addGap(18, 18, 18)
                        .addComponent(tvReleaseBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(exitBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvFillBut)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tvProcBut)
                        .addComponent(tvReleaseBut)
                        .addComponent(exitBut)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButActionPerformed
        JTVProg.logPrint("mainFrame", 2, "дана команда завершения!");
        System.exit(0);
    }//GEN-LAST:event_exitButActionPerformed

    private void tvchReleaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvchReleaseOrderActionPerformed
        tvchOrderFrame orderWindow = new tvchOrderFrame(this);
        orderWindow.setVisible(true);
    }//GEN-LAST:event_tvchReleaseOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem tvAbout;
    private javax.swing.JMenuBar tvBar;
    private javax.swing.JMenuItem tvDeleteFiles;
    private javax.swing.JButton tvFillBut;
    private javax.swing.JMenuItem tvHelp;
    private javax.swing.JMenu tvOther;
    private javax.swing.JButton tvProcBut;
    private javax.swing.JButton tvReleaseBut;
    private javax.swing.JMenu tvSettings;
    private javax.swing.JMenuItem tvchReleaseOrder;
    private javax.swing.JMenuItem tvchSettings;
    public javax.swing.JTable tvchTable;
    // End of variables declaration//GEN-END:variables
}
