/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtvprog;

/**
 *
 * @author Stanislav Nepochatov <spoilt.exile@gmail.com>
 */
public class RibbonTVSettings extends javax.swing.JDialog {

    /**
     * Creates new form RibbonTVSettings
     */
    public RibbonTVSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        channelRelease = new javax.swing.JCheckBox();
        channelDirBut = new javax.swing.JButton();
        dayDirs = new javax.swing.JTextField();
        dayRelease = new javax.swing.JCheckBox();
        channelDirs = new javax.swing.JTextField();
        dayDirBut = new javax.swing.JButton();
        allowPassedChRelease = new javax.swing.JCheckBox();
        cancelBut = new javax.swing.JButton();
        saveBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Настройки выпуска в систему \"Стрічка\"");
        setResizable(false);

        channelRelease.setText("Выпуск по каналам");

        channelDirBut.setText("Выбрать");
        channelDirBut.setEnabled(false);

        dayDirs.setEditable(false);
        dayDirs.setText("[]");

        dayRelease.setText("Выпуск по дням");

        channelDirs.setEditable(false);
        channelDirs.setText("[]");

        dayDirBut.setText("Выбрать");
        dayDirBut.setEnabled(false);

        allowPassedChRelease.setText("Позволить выпускать в систему неполную телепрограмму");

        cancelBut.setText("Отменить");

        saveBut.setText("Сохранить");
        saveBut.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBut)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(channelRelease)
                                .addGap(18, 18, 18)
                                .addComponent(channelDirs, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(channelDirBut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayRelease)
                                .addGap(44, 44, 44)
                                .addComponent(dayDirs, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayDirBut))
                            .addComponent(allowPassedChRelease))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channelRelease)
                    .addComponent(channelDirBut)
                    .addComponent(channelDirs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayDirBut)
                    .addComponent(dayDirs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayRelease))
                .addGap(18, 18, 18)
                .addComponent(allowPassedChRelease)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBut)
                    .addComponent(saveBut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RibbonTVSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RibbonTVSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RibbonTVSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RibbonTVSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RibbonTVSettings dialog = new RibbonTVSettings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowPassedChRelease;
    private javax.swing.JButton cancelBut;
    private javax.swing.JButton channelDirBut;
    private javax.swing.JTextField channelDirs;
    private javax.swing.JCheckBox channelRelease;
    private javax.swing.JButton dayDirBut;
    private javax.swing.JTextField dayDirs;
    private javax.swing.JCheckBox dayRelease;
    private javax.swing.JButton saveBut;
    // End of variables declaration//GEN-END:variables
}
