/**
 * This file is part of JTVProg application (check README).
 * Copyright (C) 2013 Stanislav Nepochatov
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/

package ribbon;

import jtvprog.JTVProg;

/**
 *
 * @author Stanislav Nepochatov <spoilt.exile@gmail.com>
 */
public class RibbonDirFrame extends javax.swing.JFrame {
    
    /**
     * Init running flag.
     */
    private Boolean initRun = true;
    
    /**
     * Text field to modify;
     */
    private javax.swing.JTextField modField;
    
    private RibbonTVSettings modDialog;

    /**
     * Creates new form RibbonDirFrame
     */
    public RibbonDirFrame(RibbonTVSettings parent, javax.swing.JTextField givenDirField) {
        initComponents();
        this.modField = givenDirField;
        this.modDialog = parent;
        String[] rawDirs = JTVProg.tvApp.appWorker.sendCommandWithCollect("RIBBON_GET_DIRS:").split("\n");
        for (String dirLine : rawDirs) {
            DirClasses.DirSchema rawSchema = new DirClasses.DirSchema(Generic.CsvFormat.parseDoubleStruct(dirLine)[1]);
            DirClasses.DirEntryUI.rootDir.insertDir("",rawSchema.FULL_DIR_NAME , rawSchema);
        }
        this.dirTree.setModel(DirClasses.DirEntryUI.rootDir);
        this.dirIndicator.setText(givenDirField.getText());
        dirTree.expandRow(0);
        dirTree.setRootVisible(false);
        String[] parsedPaths = givenDirField.getText().replaceFirst("\\[", "").replaceFirst("\\]", "").split(",");
        javax.swing.tree.TreePath[] treePaths = new javax.swing.tree.TreePath[parsedPaths.length];
        for (int index = 0; index < parsedPaths.length; index++) {
            String[] pathChain = parsedPaths[index].split("\\.");
            java.util.List<String> completePath = new java.util.ArrayList<String>();
            completePath.add(DirClasses.DirEntryUI.rootDir.DIR_NAME);
            completePath.addAll(java.util.Arrays.asList(pathChain));
            String[] pathDirChain = completePath.toArray(new String[completePath.size()]);
            DirClasses.DirEntryUI[] pathDir = new DirClasses.DirEntryUI[pathDirChain.length];
            String compDir = "";
            for (int dirIndex = 0; dirIndex < pathDirChain.length; ++dirIndex) {
                if (dirIndex == 0) {
                    pathDir[dirIndex] = DirClasses.DirEntryUI.rootDir;
                } else {
                    if (compDir.equals("")) {
                        compDir += pathDirChain[dirIndex];
                    } else {
                        compDir += "." + pathDirChain[dirIndex];
                    }
                    pathDir[dirIndex] = (DirClasses.DirEntryUI) DirClasses.DirEntryUI.rootDir.returnEndDir("", compDir);
                }
            }
            treePaths[index] = new javax.swing.tree.TreePath(pathDir);
        }
        dirTree.setExpandsSelectedPaths(true);
        dirTree.getSelectionModel().setSelectionPaths(treePaths);
        this.initRun = false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirIndicator = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dirTree = new javax.swing.JTree();
        canselBut = new javax.swing.JButton();
        selectBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Выбор направлений");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dirIndicator.setEditable(false);
        dirIndicator.setText("[]");
        dirIndicator.setOpaque(false);

        dirTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                dirTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(dirTree);

        canselBut.setText("Отмена");

        selectBut.setText("Выбрать");
        selectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dirIndicator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 185, Short.MAX_VALUE)
                        .addComponent(selectBut)
                        .addGap(18, 18, 18)
                        .addComponent(canselBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canselBut)
                    .addComponent(selectBut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dirTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_dirTreeValueChanged
        if (!initRun) {
            javax.swing.tree.TreePath[] pathes = dirTree.getSelectionPaths();
            String[] dirStrings = new String[pathes.length];
            for (Integer selIndex = 0; selIndex < pathes.length; selIndex++) {
                dirStrings[selIndex] = DirClasses.DirEntryUI.getEndDir(pathes[selIndex]).FULL_DIR_NAME;
            }
            this.dirIndicator.setText(Generic.CsvFormat.renderGroup(dirStrings));
        }
    }//GEN-LAST:event_dirTreeValueChanged

    private void selectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButActionPerformed
        this.modField.setText(this.dirIndicator.getText());
        this.modDialog.unlockButs();
        this.dispose();
    }//GEN-LAST:event_selectButActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.modDialog.unlockButs();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RibbonDirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RibbonDirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RibbonDirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RibbonDirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RibbonDirFrame(new RibbonTVSettings(null, false), new javax.swing.JTextField()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canselBut;
    public javax.swing.JTextField dirIndicator;
    private javax.swing.JTree dirTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectBut;
    // End of variables declaration//GEN-END:variables
}
